### ISSUE TITLE
Docker ( for synology )

### ISSUE THREAD

**Issue by bozzfozz** [btcz/bitcoinz-seeder#1]
what is with a docker image , 
can you make one ?

so you could quickly get many seed to run

**Comment by ghost** [comment]
Good idea! Anyone would like to create & share docker image in his github repo?

**Comment by renuzit** [comment]
PR Submitted:  https://github.com/bitcoinz-pod/bitcoinz-seeder/pull/2

**Comment by ghost** [comment]
done
